modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/tasgon/observable/issues"
license = "MPL"

[[mods]]
modId = "observable"
version = "${version}"
displayName = "Observable"
authors = "tasgon"
displayURL = "https://github.com/tasgon/observable"
description = '''
See what's lagging your world.
'''
#logoFile = ""

[[dependencies.observable]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.observable]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.observable]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"

# [[dependencies.observable]]
# modId = "kotlinforforge"
# mandatory = true
# versionRange = "[1.11.0,)"
# ordering = "AFTER"
# side = "BOTH"