modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/tasgon/observable/issues"
authors = "tasgon"
license = "MPL"

[[mods]]
modId = "observable"
version = "${version}"
displayName = "Observable"
description = '''
See what's lagging your world.
'''

[[dependencies.observable]]
modId = "architectury"
type = "required"
versionRange = "[8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.observable]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "observable.common.json"

# [[dependencies.observable]]
# modId = "kotlinforforge"
# mandatory = true
# versionRange = "[1.11.0,)"
# ordering = "AFTER"
# side = "BOTH"
