repos:
  - repo: local
    hooks:
      - id: ktlint
        name: ktlint
        files: .*\.(kt|gradle)
        entry: bash -c "./gradlew ktlintFormat"
        language: system
        pass_filenames: false